BEGIN TRANSACTION;

CREATE DATABASE DATASET

CREATE TABLE IF NOT EXISTS "tb_DataSet" (
	"code"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	"Detectado"	TEXT NOT NULL,
	"Acuracia"	TEXT NOT NULL,
	"Data_stamp"	TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS "tb_veiculos" (
	"code"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	"imagen"	BLOB NOT NULL,
	"Detectado"	INTEGER NOT NULL,
	"Acuracia"	TEXT NOT NULL,
	"id_resultado"	INTEGER NOT NULL UNIQUE
);
CREATE TABLE IF NOT EXISTS "tb_objeto" (
	"code"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	"imagen"	BLOB NOT NULL,
	"Detectado"	INTEGER NOT NULL,
	"Acuracia"	TEXT NOT NULL,
	"id_resultado"	INTEGER NOT NULL UNIQUE
);
CREATE TABLE IF NOT EXISTS "tb_pessoa" (
	"code"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	"imagen"	BLOB NOT NULL,
	"Detectado"	INTEGER NOT NULL,
	"Acuracia"	TEXT NOT NULL,
	"id_resultado"	INTEGER NOT NULL UNIQUE
);
CREATE TABLE IF NOT EXISTS "tb_resultados" (
	"code"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	"imagen"	BLOB NOT NULL,
	"Detectado"	INTEGER NOT NULL,
	"Acuracia"	TEXT NOT NULL,
	"id_user"	INTEGER NOT NULL UNIQUE
);
COMMIT;
